from distutils.core import setup

setup(
    name='lcd-screen-piface',
    version='1.0.0',
    packages=['venv.lib.python3.5.distutils', 'venv.lib.python3.5.encodings', 'venv.lib.python3.5.importlib',
              'venv.lib.python3.5.collections', 'venv.lib.python3.5.site-packages.pip',
              'venv.lib.python3.5.site-packages.pip.req', 'venv.lib.python3.5.site-packages.pip.vcs',
              'venv.lib.python3.5.site-packages.pip.utils', 'venv.lib.python3.5.site-packages.pip.compat',
              'venv.lib.python3.5.site-packages.pip.models', 'venv.lib.python3.5.site-packages.pip._vendor',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations',
              'venv.lib.python3.5.site-packages.wheel', 'venv.lib.python3.5.site-packages.wheel.tool',
              'venv.lib.python3.5.site-packages.wheel.signatures', 'venv.lib.python3.5.site-packages.pifacecad',
              'venv.lib.python3.5.site-packages.pifacecad.tools', 'venv.lib.python3.5.site-packages.setuptools',
              'venv.lib.python3.5.site-packages.setuptools.extern',
              'venv.lib.python3.5.site-packages.setuptools.command', 'venv.lib.python3.5.site-packages.pifacecommon',
              'venv.lib.python3.5.site-packages.pkg_resources', 'venv.lib.python3.5.site-packages.pkg_resources.extern',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging', 'pager'],
    url='https://github.com/keigezellig/lcd-screen-piface',
    license='THE APPRECIATION LICENSE',
    author='M. Joosten',
    author_email='',
    description='Some modules to create screens more easily for a Piface CAD 2'
)
